# Generated by Django 5.0.4 on 2024-04-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_car_delete_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='c_model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
